export const dynamic = "force-dynamic";
import Header from "./components/header";
import BlogPage from "./pages/Blog-page";
import { getBlogs } from "@/lib/blogs";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  const blogs = getBlogs();
  return (
    <div className="h-screen">
      <Header />
      <div className="bg-[#FBFCFE] ">
        <BlogPage blogs={blogs} />
      </div>
    </div>
  );
}
